# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: membership.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='membership.proto',
  package='membership',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10membership.proto\x12\nmembership\"\x9b\x01\n\x05\x45vent\x12.\n\teventType\x18\x01 \x02(\x0e\x32\x1b.membership.Event.EventType\x12\x10\n\x08memberId\x18\x02 \x02(\t\x12\x10\n\x08memberIp\x18\x03 \x02(\t\x12\x12\n\nmemberPort\x18\x04 \x02(\x05\"*\n\tEventType\x12\x08\n\x04JOIN\x10\x00\x12\t\n\x05LEAVE\x10\x01\x12\x08\n\x04\x46\x41IL\x10\x02\"\xc5\x01\n\x07PingAck\x12\x10\n\x08sourceId\x18\x01 \x02(\t\x12\x0e\n\x06seqNum\x18\x02 \x02(\x05\x12,\n\x07msgType\x18\x03 \x02(\x0e\x32\x1b.membership.PingAck.MsgType\x12!\n\x06\x65vents\x18\x04 \x03(\x0b\x32\x11.membership.Event\x12\x10\n\x08targetId\x18\x05 \x01(\t\"5\n\x07MsgType\x12\x08\n\x04PING\x10\x00\x12\x07\n\x03\x41\x43K\x10\x01\x12\x0b\n\x07PINGREQ\x10\x02\x12\n\n\x06\x41\x43KREQ\x10\x03')
)



_EVENT_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='membership.Event.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JOIN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=146,
  serialized_end=188,
)
_sym_db.RegisterEnumDescriptor(_EVENT_EVENTTYPE)

_PINGACK_MSGTYPE = _descriptor.EnumDescriptor(
  name='MsgType',
  full_name='membership.PingAck.MsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PINGREQ', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACKREQ', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=335,
  serialized_end=388,
)
_sym_db.RegisterEnumDescriptor(_PINGACK_MSGTYPE)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='membership.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventType', full_name='membership.Event.eventType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memberId', full_name='membership.Event.memberId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memberIp', full_name='membership.Event.memberIp', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memberPort', full_name='membership.Event.memberPort', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENT_EVENTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=188,
)


_PINGACK = _descriptor.Descriptor(
  name='PingAck',
  full_name='membership.PingAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sourceId', full_name='membership.PingAck.sourceId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqNum', full_name='membership.PingAck.seqNum', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='membership.PingAck.msgType', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='events', full_name='membership.PingAck.events', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetId', full_name='membership.PingAck.targetId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PINGACK_MSGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=388,
)

_EVENT.fields_by_name['eventType'].enum_type = _EVENT_EVENTTYPE
_EVENT_EVENTTYPE.containing_type = _EVENT
_PINGACK.fields_by_name['msgType'].enum_type = _PINGACK_MSGTYPE
_PINGACK.fields_by_name['events'].message_type = _EVENT
_PINGACK_MSGTYPE.containing_type = _PINGACK
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['PingAck'] = _PINGACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'membership_pb2'
  # @@protoc_insertion_point(class_scope:membership.Event)
  ))
_sym_db.RegisterMessage(Event)

PingAck = _reflection.GeneratedProtocolMessageType('PingAck', (_message.Message,), dict(
  DESCRIPTOR = _PINGACK,
  __module__ = 'membership_pb2'
  # @@protoc_insertion_point(class_scope:membership.PingAck)
  ))
_sym_db.RegisterMessage(PingAck)


# @@protoc_insertion_point(module_scope)
