# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingAck.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pingAck.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rpingAck.proto\x12\x08tutorial\"\xb2\x01\n\x07pingAck\x12\x10\n\x08sourceId\x18\x01 \x02(\x05\x12\x0e\n\x06seqNum\x18\x02 \x02(\x05\x12\r\n\x05isAck\x18\x03 \x02(\x08\x12+\n\x04type\x18\x04 \x02(\x0e\x32\x1d.tutorial.pingAck.messageType\x12\x0f\n\x07members\x18\x05 \x03(\x05\"8\n\x0bmessageType\x12\n\n\x06NORMAL\x10\x00\x12\x08\n\x04JOIN\x10\x01\x12\t\n\x05LEAVE\x10\x02\x12\x08\n\x04\x46\x41IL\x10\x03')
)



_PINGACK_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='messageType',
  full_name='tutorial.pingAck.messageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOIN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAVE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=150,
  serialized_end=206,
)
_sym_db.RegisterEnumDescriptor(_PINGACK_MESSAGETYPE)


_PINGACK = _descriptor.Descriptor(
  name='pingAck',
  full_name='tutorial.pingAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sourceId', full_name='tutorial.pingAck.sourceId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqNum', full_name='tutorial.pingAck.seqNum', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isAck', full_name='tutorial.pingAck.isAck', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='tutorial.pingAck.type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='members', full_name='tutorial.pingAck.members', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PINGACK_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=206,
)

_PINGACK.fields_by_name['type'].enum_type = _PINGACK_MESSAGETYPE
_PINGACK_MESSAGETYPE.containing_type = _PINGACK
DESCRIPTOR.message_types_by_name['pingAck'] = _PINGACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

pingAck = _reflection.GeneratedProtocolMessageType('pingAck', (_message.Message,), dict(
  DESCRIPTOR = _PINGACK,
  __module__ = 'pingAck_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.pingAck)
  ))
_sym_db.RegisterMessage(pingAck)


# @@protoc_insertion_point(module_scope)
